    image: jangrewe/gitlab-ci-android
    stages:
    - build
    before_script:
    - export GRADLE_USER_HOME=$(pwd)/.gradle
    - chmod +x ./gradlew
    cache:
      key: ${CI_PROJECT_ID}
      paths:
      - .gradle/
    build:
      stage: build
      script:
      - ./gradlew assembleDebug
      artifacts:
        paths:
        - app/build/outputs/apk/debug/
    deploy:
      stage: deploy
      only:
        - master
      script:
        - |
          curl \
          -A "GitLab CI" \
          -F api_key="${TESTFAIRY_API_KEY}" \
          -F comment="GitLab Pipeline build ${CI_COMMIT_SHA}" \
          -F file=app/build/outputs/apk/debug/app-debug.apk \
          https://upload.testfairy.com/api/upload/
      dependencies:
        
        - build