version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
      - image: circleci/node:8-browsers
    environment:
      JVM_OPTS: -Xmx4G
    steps:
      - checkout
      - run: echo "Mirkelam is working for you 👯"
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: sudo chmod +x ./gradlew
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
                path: app/build/test-results
                destination: test-results/
      - checkout
      - run: npm install
      - run: npx gulp build
      - run: node .circleci/deploy.js
      - run: echo "WE'RE ONLINE"