version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/android:api-28-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: echo "Mirkelam is working for you 👯"
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: sudo chmod +x ./gradlew
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: "Install ionic and cordova"
          command: |
            sudo npm install -g ionic cordova yarn
      - run:
          name: "Install npm packages"
          command: |
            yarn install
      - run:
          name: "Install Cordova plugins and add android platform"
          command: |
            ionic cordova platform add android --noresources
            ionic config set -g telemetry true
      - run:
          name: "Generate apk"
          command: |
            ionic cordova build android --verbose
            mkdir -p /tmp/apk
            cp -r platforms/android/app/build/outputs/apk/debug/app-debug.apk /tmp/apk
      - store_artifacts:
          path: /tmp/apk
          destination: apks
 