version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
      - image: circleci/node:10
    environment:
      JVM_OPTS: -Xmx4G
    steps:
      - checkout
      # Download and cache dependencies.
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # Fallback to using the latest cache if no exact match is found.
          - v1-dependencies-
      - run:
          name: Download Dependencies
          command: |
            sudo chmod +x gradlew
            ./gradlew androidDependencies 
      - run: yes | sdkmanager --licenses || exit 0
      - run: yes | sdkmanager --update || exit 0

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
                path: app/build/test-results
                destination: test-results/
      - checkout
      - run:
          name: Initial build
          command: ./gradlew clean assembleRelease --no-daemon --stacktrace
      # Run the FTP deployment script.
      - run: npm run ftp-deploy